name: CI

on:
  push:
    branches:
      - master
    tags:
      - 1.*

env:
  FLUTTER_VERSION: "3.10.x"

jobs:
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    env:
      working-directory: ./example
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - name: Dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}
      - name: Build APK
        working-directory: ${{env.working-directory}}
        run: flutter build apk --debug
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    env:
      working-directory: ./example
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
          architecture: x64
      - name: Dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}
      - name: Build IPA
        working-directory: ${{env.working-directory}}
        run: flutter build ios --release --no-codesign
