name: CI

on: pull_request

env:
  FLUTTER_VERSION: "3.10.x"
  WORKING_DIRECTORY: ./example

jobs:
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - name: Dependencies
        run: flutter pub get
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Build APK
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: flutter build apk --debug
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
          architecture: x64
      - name: Dependencies
        run: flutter pub get
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Build IPA
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: flutter build ios --release --no-codesign
